version: '3.7'
services:
  node:
    container_name: sample_node
    restart: always
    build:
      context: ./docker/.
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    environment:
          - CHOKIDAR_USEPOLLING=true
    depends_on:
      - mysql
    networks:
      - dbnet
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "23306:23306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"
    networks:
      - dbnet

volumes:
  db-data:
networks:
  dbnet: