version: '3.7'
services:
  node:
    container_name: sample_node
    hostname: node_host
    restart: always
    build:
      context: ./docker/.
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    tty: true
    environment:
          - CHOKIDAR_USEPOLLING=true
    depends_on:
      - db
    networks:
      - dbnet
  db:
    container_name: sample_db
    hostname: mysql_host
    image: "mysql:5.7"
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "database"
    networks:
      - dbnet

networks:
  dbnet: